repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0  # pin to a specific Ruff version
    hooks:
      - id: ruff-check
        args: [--fix]
        exclude: ^DRAFT*
      - id: ruff-format
        exclude: ^DRAFT*

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.400
    hooks:
      - id: pyright
        exclude: ^DRAFT*
