repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0  # pin to a specific Ruff version
    hooks:
      - id: ruff-check
        args: [--fix]
        exclude: ^drafting*
      - id: ruff-format
        exclude: ^drafting*

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.400
    hooks:
      - id: pyright
        exclude: ^drafting*

  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: uv run python -m pytest tests/
        language: system
        types: [python]
        pass_filenames: false
        always_run: false
        exclude: ^drafting*
